version: '3.0'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "8080:80"
    volumes:
      - ./volumes/magento/vendor/addressfinder:/var/www/html/vendor/addressfinder
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    ports:
      - "33060:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
